### ISSUE TITLE
Feature request: Copy over "sessions" folder.

### ISSUE THREAD

**Issue by hunter-nl** [nrlquaker/winbox-mac-addresses#1]
The sessions folder ```/Users/<username>/Library/Application Support/com.mikrotik.winbox_<version>/drive_c/users/<username>/Application Data/Mikrotik/Winbox/sessions``` contains like window size, columns, sorting, and other settings for each session connection to a device. It would be very nice if this can also be copied over. I do it now manually every time.

**Comment by nrlquaker** [comment]
@hunter-nl What about `/Users/<username>/Library/Application Support/com.mikrotik.winbox_<version>/drive_c/users/<username>/Application Data/Mikrotik/Winbox/sessionpath`? Is it needed as well?

**Comment by nrlquaker** [comment]
`sessionpath` is not needed as its created at launch.

**Comment by hunter-nl** [comment]
It is not needed, if it does not exist, it will be recreated. As long as the sessions folder has not be changed from default location. It does not harm to copy this file also.
The file ```/Users/<username>/Library/Application Support/com.mikrotik.winbox_<version>/drive_c/users/<username>/Application Data/Mikrotik/Winbox/settings.cfg.viw``` is needed also to keep settings (settings like Advanced mode, Keep Password, Autosave Session, etc) of the main window showing the device addresses.

**Comment by nrlquaker** [comment]
I've added changes to copy `sessions` folders. Will add ability to copy `settings.cfg.viw` as well.

**Comment by nrlquaker** [comment]
Added in [0.2.0](https://github.com/nrlquaker/winbox-mac-addresses/releases/tag/v0.2.0). This version will be included in next `Winbox-mac` release.
